version: '3.9'

services:
  postgres:
    image: postgres:14
    container_name: archive1_db_dbonly
    ports:
      - "8011:5432"
    environment:
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
      - POSTGRES_DB=${DB_NAME:-archive1}
    volumes:
      - archive1_dbonly_v:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime

volumes:
  archive1_dbonly_v: