###
# This file is a example of .agent1.yaml configuration
###

# Address to target archivo server which this agent should call
archivo_server: "https://server.archivo.io"

# Target archivo name for this agent (oauth actions)
agent_name: "example-agent"

# Target archivo key for this agent (oauth actions)
agent_key: "thisismysampleapikeyfromarchivo"

# Files that agent1 should send to archivo server to backup temporarily
files:
  - filename: "file1-custom-name"
    path: "/absolute/path/to/file1"
    interval: "1 * * * *" # use crontab style to specify interval
    rotate: 3 # backup counts on archivo server. minimum is 1

  - path: "/absolute/path/to/file2"
    interval: "@daily" # every day
    rotate: 100

  - path: "/absolute/path/to/file3"
    interval: "@every 5m" # every five minutes
    rotate: 1