###
# This file is a example of .agent1.yaml configuration
###

# Address to target archive1 server which this agent should call
archive1_server: "https://server.archive1.io"

# Target archive1 name for this agent (oauth actions)
agent_name: "example-agent"

# Target archive1 key for this agent (oauth actions)
agent_key: "thisismysampleapikeyfromarchive1"

# Files that agent1 should send to archive1 server to backup temporarily
files:
  - path: "/absolute/path/to/file1"
    interval: "1 * * * *" # use crontab style to specify interval
    rotate: 3 # backup counts on archive1 server. minimum is 1

  - path: "/absolute/path/to/file2"
    interval: "@daily" # every day
    rotate: 100

  - path: "/absolute/path/to/file3"
    interval: "@every 5m" # every five minutes
    rotate: 1