package validate

const (
	MessageRequired              = "%s is required"
	MessageLen                   = "%s must be exactly %s characters long"
	MessageMin                   = "%s must be at least %s characters long"
	MessageMax                   = "%s must be at most %s characters long"
	MessageEqual                 = "%s must be equal to %s"
	MessageNotEqual              = "%s must not be equal to %s"
	MessageOneOf                 = "%s must be one of %s"
	MessageLessThan              = "%s must be less than %s"
	MessageLessThanEqual         = "%s must be less than or equal to %s"
	MessageGreaterThan           = "%s must be greater than %s"
	MessageGreaterThanEqual      = "%s must be greater than or equal to %s"
	MessageEqualField            = "%s must be equal to %s"
	MessageNotEqualField         = "%s must not be equal to %s"
	MessageGreaterThanField      = "%s must be greater than %s"
	MessageGreaterThanEqualField = "%s must be greater than or equal to %s"
	MessageLessThanField         = "%s must be less than %s"
	MessageLessThanEqualField    = "%s must be less than or equal to %s"
	MessageAlpha                 = "%s must contain only letters"
	MessageAlphaNum              = "%s must contain only letters and numbers"
	MessageAlphaUnicode          = "%s must contain only Unicode letters"
	MessageAlphaNumUnicode       = "%s must contain only Unicode letters and numbers"
	MessageNumeric               = "%s must be a numeric value"
	MessageNumber                = "%s must be a number"
	MessageHexadecimal           = "%s must be a hexadecimal number"
	MessageEmail                 = "%s must be a valid email address"
	MessageURL                   = "%s must be a valid URL"
	MessageURI                   = "%s must be a valid URI"
	MessageBase64                = "%s must be a valid base64-encoded string"
	MessageContains              = "%s must contain %s"
	MessageContainsAny           = "%s must contain at least one of the following characters: %s"
	MessageExcludes              = "%s may not contain %s"
	MessageExcludesAll           = "%s may not contain any of the following characters: %s"
	MessageExcludesRune          = "%s may not contain the following character: %s"
	MessageUUID                  = "%s must be a valid UUID"
	MessageUUID3                 = "%s must be avalid UUIDv3"
	MessageUUID4                 = "%s must be a valid UUIDv4"
	MessageUUID5                 = "%s must be a valid UUIDv5"
	MessageDataURI               = "%s must be a valid data URI"
	MessageIPv4                  = "%s must be a valid IPv4 address"
	MessageIP                    = "%s must be a valid IP address"
	MessageBoolean               = "%s must ba a valid Boolean"
	MessageGroupInvalid          = "%s is invalid. must be %s"
	MessageCron                  = "%s must be valid cron schedule"
	MessagePassword              = "%s is not a strong password"
)
