###
# This file is a example of .archivo.yaml configuration
###

# Archivo server host (optional. default is 0.0.0.0)
server_host: "0.0.0.0"

# Archivo server port (optional. default is 8010)
server_port: 8010

# Archivo postgres database configuration (required)
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "<CHANGE-PASSWORD>"
  timezone: "Asia/Tehran"
  ssl_mode: false
  ## database name
  dbname: "archivo"

auth:
  jwt_secret: "<CHANGE-JWT-SECRET>"
  # Example: 5m (5 minutes), 1h10m (one hour and ten minutes) 
  jwt_expire_time: "5m"

file_store:
  mode: "disk"
  disk_config:
    path: "/usr/archivo"
